version: '3.8'

services:
  flask:
    build: .
    expose:
      - "8000"
    networks:
      - appnet

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    depends_on:
      - flask
    networks:
      - appnet

networks:
  appnet:
